### ISSUE TITLE
Repo with coded designs

### ISSUE THREAD

**Issue by gridchin** [tes/app-styleguide#10]
While speaking with US designers they expressed their need of having different URLs for each page they design. For example:

http://gridchin.com/tes/storefront/cards.html
http://gridchin.com/tes/storefront/collection.html
http://gridchin.com/tes/storefront/rdp-elements.html
etc.

These pages will be permanent, so designers will have access to them any time. For that we will need the possibility of creating new hbs and assigning them new URLs. It can be something like:

https://tes.com/styleguide/playground/cards/
https://tes.com/styleguide/playground/collection/
https://tes.com/styleguide/playground/rdp-elements/
etc. 

Or may be we can setup an environment in `Frontend` repository (https://github.com/tes/frontend) where we can create these pages based on the hbs&scss from `module-tsl-ui-components` components and with services (specially styles) from `service-site-assets`. These pages can live on gh-pages URLs:

http://tes.github.io/frontend/storefront/cards/
http://tes.github.io/frontend/storefront/collection/
http://tes.github.io/frontend/storefront/rdp-elements/
etc.

We will keep placing individual components in `app-styleguide` as we discussed. This request is for pages composed by components and other design elements, with review purpose only.

Any suggestions are very welcome @jonnywyatt @michaelcrowe @cjcheshire 
CC @eddie-leo @clare3000

**Comment by jonnywyatt** [comment]
Hi, sounds fine to me for the pages to live in either place, I'd just like to ensure that components are only developed with access to tes-sass and module-tsl-ui-components, and if we need anything extra (from tes-sass-resources) we only copy over the minimum necessary from it to tes-sass. Then we'll ensure that the components are portable and can be compiled in any app. Does that sound ok?

**Comment by cliftonc** [comment]
My preference would be to keep them in the style-guide to reduce moving parts, risk of creep away from tes-sass etc. ensure everyone has full visibility of whats being added.

**Comment by gridchin** [comment]
Components will be developed only with `tes-sass` and `module-tsl-ui-components`. In the future with everything componentized I think there will be no need in `tes-sass-resources`. Please let us know where and how to approach the creation of new hbs for these pages.

**Comment by jonnywyatt** [comment]
@gridchin feel free to add as many routes as you need to app-styleguide then, whatever you need to support your work. Check the last commit adding /playground route for an example.

**Comment by gridchin** [comment]
great, thank you Jonathan.

**Comment by cjcheshire** [comment]
I've updated the routes so /styleguide/playground loads the index.hbs in the folder.
 
I've added a cards file as an example, but you can add whatever you like in there and access it from /styleguide/playground/filename.

**Comment by gridchin** [comment]
Awesome!! Thank you @cjcheshire
