### ISSUE TITLE
Date format style

### ISSUE THREAD

**Issue by gilgongo** [tes/app-styleguide#19]
This is the approved date style. 

## Please read entire spec before deciding which you should use! 

**For EBUS**

Long format: eg "**09 Jun 2016 02:15pm**"
Short: eg "**09 Jun 2016**"

**For US**

Long format: eg "**Jun 09 2016 02:15pm**"
Short: eg "**Jun 09 2016**"

**Guidelines**

Use Long format when time of day is important (eg logs of actions, comments, or when an event might not reasonably be assumed to take place at midnight).

Use ordinals "Today" to "Yesterday", when general recency is important (eg resources uploaded or applicants applied), then use Short form after that.

Use fine-grained ordinals for news items or similar "breaking" content. Use "Just now" to "23 hours ago" to "One day ago" to "Six days ago", then use Short format.

All other dates take Short format.

**Rationale**

Overall, we're trying for brevity (so no punctuation, leading zeros and stuff), immediate clarity (hence ordinals like "today" and "2 hours ago") and allow for any international issues. We also think that 24 clock is too geeky, so willing to sacrifice a few pixels for am/pm.

**NOTE**: If location switching is going to be a problem, just use US format because people in the US are sensitive to these things. Whereas EBUS don't givvashit really.

**Comment by heyamylin** [comment]
Providing the US perspective here, dd-mm-yyyy format is a bit more foreign here and the 24h format is even more foreign. 

If possible, we should have US friendly format:
Short: **Jun 9 2016**
Long: **Jun 9 2016 2:15pm**

**Comment by gilgongo** [comment]
Good call - we should really have the ability to change formats per geo in any case. At the very least it'll be necessary for the Chinese site, for example.

**Comment by MikaelaB** [comment]
If time is at the end I think it's easier to read, saves hunting it out.

For EBUS

Long format: eg "9 Jun 2016, 14:15"
Short: eg "9 Jun 2016"

For US

Long format: eg "Jun 9 2016, 2:15pm"
Short: eg "Jun 9 2016"

**Comment by MikaelaB** [comment]
Also, @Fetz pointed us to this: http://momentjs.com/

**Comment by gilgongo** [comment]
Yes Chris mentioned moment.js but I'm not sure how thats  relevant here?

**Comment by MikaelaB** [comment]
@gilgongo 

Thanks for putting the time after date. The other question discussed was should time format (everywhere other than US) be the 24hr clock?

**Comment by cjcheshire** [comment]
Just to clarify 'news'.  Do you mean the news section of the website or does that stretch further to the feed?  The feed benefits from the today, 2 hours ago, yesterday too.

**Comment by gilgongo** [comment]
@MikaelaB I added a line to the rationale about 24-hour clock, based on a feeling I got in conversations with some people.

@cjcheshire Yes, "news" could also be the feed since this also benefits from a clear indication of degree of freshness (the idea being that "2 hours ago" is punchier than "Jun 12, 4:20pm").

We should probably try to come up with a guideline on how far to use to use ordinal (?) stamps like this though. So in the the case of things that benefit from being fresh, perhaps stop at "23 hours ago" and then start using short form dates. For things that benefit from "general" recency like resources or comments on something, we could just say "today", "yesterday" and then drop to short form after that?

**Comment by cjcheshire** [comment]
@gilgongo yea that makes sense.  My gut says is it's stale after a week, so we go up to 6 days ago.  The time in the news type instances becomes less relevant after that period.  The date (no time) published feels enough – thoughts?  Perhaps that rule would work for anything one off, but things like comments would benefit from the time more.

**Comment by gilgongo** [comment]
@cjcheshire OK I'll add that to the guidelines.

**Comment by MikaelaB** [comment]
Back then, when this issue arose. Moments seemed relevant as TES could potentially use it. It covered display date format be it long, short or relative. I also wondered about converting dates between time zones.

**Comment by gilgongo** [comment]
Oh OK. No constraint implied on the desired style I hope then.

**Comment by cjcheshire** [comment]
@gilgongo I haven't mentioned moment here.

I have offline as it's been used in various places already.  As far as I can tell it will comply with all your thoughts above.  It has been mentioned as it's a very useful library when dates are concerned, rather than trying to do all the above ourselves.

**Comment by gilgongo** [comment]
@cjcheshire OK sure. Just needed to clarify that to avoid getting distracted by implementation issues.

**Comment by cjcheshire** [comment]
Agreed, that's why I didn't mention it above ;)

**Comment by gilgongo** [comment]
Various comments from the team now incorporated into the ticket.

**Comment by gilgongo** [comment]
Hm. I see why people have leading zeroes now. Maybe we should have them after all?

![image](https://cloud.githubusercontent.com/assets/4561747/16732410/ee69e74e-4774-11e6-8634-a4b79e74193d.png)

**Comment by clare3000** [comment]
Any standards on how we format timezones?

**Comment by gilgongo** [comment]
@clare3000 Not sure what you mean, but can you offer some suggestions?

**Comment by clare3000** [comment]
The current sale tool spells out timezones: 
![image](https://cloud.githubusercontent.com/assets/10792514/16999497/24622550-4e73-11e6-9d24-38dd7a1ffdf6.png)

Should we go this route or use the standard abbreviations? Non-abbreviated is a little easier to understand.

**Comment by gilgongo** [comment]
So this is for allowing people to sell stuff optimally in other territories? 

If so, I'd say that was too much of an edge case to have a rule about, since 99% of cases we wouldn't bother people with time zones.

**Comment by MikaelaB** [comment]
Can we do more with the label and get repetition of 'time' out of options. Also, the UK doesn't have a London time. 

With daylight saving perhaps we shouldn't state it as 'midnight'.

Label: Which timezone should the sale begin:

US Pacific
US Eastern
UK

**Comment by clare3000** [comment]
@MikaelaB for the example UI above, please see discussion and add comments here: https://github.com/tes/resources/issues/3417

**Comment by MikaelaB** [comment]
@clare3000 Thanks, dropdown much better.

**Comment by gilgongo** [comment]
@MikaelaB Good opportunity to justify that against [this suggestion](https://github.com/tes/app-styleguide/issues/20) :-)

**Comment by tomruttle** [comment]
Is there a wiki somewhere where these sorts of standards are centralised? I had no idea we had a TES House Date Style until I happened across an issue that linked to this one.

For comparison, ATS uses five different date formats:

```

const timeFormats = {
  TIMEZONE: 'Europe/London',
  APPLICATION: 'MMMM Do YYYY',
  AUDIT: 'DD MMM YY HH:mm',
  COMMENT: 'Do MMM YYYY [at] HH:mm',
  JOB: 'D MMM YYYY',
  JOB_DATETIME: 'HH:mm, D MMM',
};
```

**Comment by gilgongo** [comment]
This ticket, for want of a better place, is where we have this.  Had hoped that we'd have the ability to add stuff to the tes.com/styleguide (which would be the obvious place) but that's not currently possible.

**Comment by cjcheshire** [comment]
We can add anything you like to the styleguide!

**Comment by cjcheshire** [comment]
Within reason ;)

**Comment by gilgongo** [comment]
In that can I repeat my hope that we can have an editable field available under each pattern (not "comments" or any such sophistication - just a plain text field). And an editable section of the style guide into which we can put things like the content of this ticket.

**Comment by gilgongo** [comment]
Closing and summarising on UX Wiki: https://github.com/tes/UX-and-Design/wiki/Date-&-Time-Format
